# Generated by Django 4.2.11 on 2024-04-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_id", models.CharField(max_length=10)),
                ("report", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
