# Generated by Django 4.2.11 on 2024-04-28 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_report_delete_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="image_name",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 4, 28, 7, 34, 10, 179894, tzinfo=datetime.timezone.utc
                ),
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
